# Use node_js environnement
language: node_js
node_js:
  - "8"

# Cache Gcloud SDK between commands
cache:
  yarn: true
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

script:
  - echo "skipping tests"

# Set env vars
env:
    global:
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - PROJECT_ID="docspace-213816"
    - ZONE="us-central1-a"
    - IMAGE_NAME=docspace:latest
    - FULL_IMAGE_NAME=gcr.io/docspace-213816/docspace
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - CLUSTER_NAME=docspace-cluster

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./deploy-staging.sh
    skip_cleanup: true
    on:
      branch: feature/deploy
  - provider: script
    script: ./deploy-production.sh
    skip_cleanup: true
    on:
      branch: master