// GET
export const GET_ALL_GROUPS_REQUEST = 'GET_ALL_GROUPS_REQUEST'
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS'
export const GET_ALL_GROUPS_ERROR = 'GET_ALL_GROUPS_ERROR'

export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST'
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS'
export const GET_GROUP_ERROR = 'GET_GROUP_ERROR'
// POST
export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST'
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR'

// UPDATE
export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_ERROR = 'UPDATE_GROUP_ERROR'

// DELETE
export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR'
