// GET
export const GET_ALL_GROUPS_REQUEST = 'GET_ALL_GROUPS_REQUEST'
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS'
export const GET_ALL_GROUPS_ERROR = 'GET_ALL_GROUPS_ERROR'
// POST
export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST'
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR'
