
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_ERROR = 'SEARCH_ERROR'

export const CLEAN_SEARCH_RESULTS = 'CLEAN_SEARCH_RESULTS'

export const ADVANCED_SEARCH_REQUEST = 'ADVANCED_SEARCH_REQUEST'
export const ADVANCED_SEARCH_SUCCESS = 'ADVANCED_SEARCH_SUCCESS'
export const ADVANCED_SEARCH_ERROR = 'ADVANCED_SEARCH_ERROR'

export const CLEAN_ADVANCED_SEARCH_RESULTS = 'CLEAN_ADVANCED_SEARCH_RESULTS'
