export const ADD_WATCHER_REQUEST = 'ADD_WATCHER_REQUEST'
export const ADD_WATCHER_SUCCESS = 'ADD_WATCHER_SUCCESS'
export const DELETE_WATCHER_REQUEST = 'DELETE_WATCHER_REQUEST'
export const DELETE_WATCHER_SUCCESS = 'DELETE_WATCHER_SUCCESS'

export const ADD_WATCHER_SPACE_REQUEST = 'ADD_WATCHER_SPACE_REQUEST'
export const ADD_WATCHER_SPACE_SUCCESS = 'ADD_WATCHER_SPACE_SUCCESS'
export const DELETE_WATCHER_SPACE_REQUEST = 'DELETE_WATCHER_SPACE_REQUEST'
export const DELETE_WATCHER_SPACE_SUCCESS = 'DELETE_WATCHER_SPACE_SUCCESS'
