export const PUT_LIKE_REQUEST = 'PUT_LIKE_REQUEST'
export const PUT_LIKE_SUCCESS = 'PUT_LIKE_SUCCESS'

export const DELETE_LIKE_REQUEST = 'DELETE_LIKE_REQUEST'
export const DELETE_LIKE_SUCCESS = 'DELETE_LIKE_SUCCESS'
