export const PUT_LIKE_ON_PAGE_REQUEST = 'PUT_LIKE_ON_PAGE_REQUEST'
export const PUT_LIKE_ON_PAGE_SUCCESS = 'PUT_LIKE_ON_PAGE_SUCCESS'
export const PUT_LIKE_ON_PAGE_ERROR = 'PUT_LIKE_ON_PAGE_ERROR'

export const DELETE_LIKE_FROM_PAGE_REQUEST = 'DELETE_LIKE_FROM_PAGE_REQUEST'
export const DELETE_LIKE_FROM_PAGE_SUCCESS = 'DELETE_LIKE_FROM_PAGE_SUCCESS'
export const DELETE_LIKE_FROM_PAGE_ERROR = 'DELETE_LIKE_FROM_PAGE_ERROR'

export const PUT_LIKE_ON_COMMENT_REQUEST = 'PUT_LIKE_ON_COMMENT_REQUEST'
export const PUT_LIKE_ON_COMMENT_SUCCESS = 'PUT_LIKE_ON_COMMENT_SUCCESS'
export const PUT_LIKE_ON_COMMENT_ERROR = 'PUT_LIKE_ON_COMMENT_ERROR'

export const DELETE_LIKE_FROM_COMMENT_REQUEST = 'DELETE_LIKE_FROM_COMMENT_REQUEST'
export const DELETE_LIKE_FROM_COMMENT_SUCCESS = 'DELETE_LIKE_FROM_COMMENT_SUCCESS'
export const DELETE_LIKE_FROM_COMMENT_ERROR = 'DELETE_LIKE_FROM_COMMENT_ERROR'
