
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'
export const CLEAR_NOTIFICATIONS_SUCCESS = 'CLEAR_NOTIFICATIONS_SUCCESS'
export const CLEAR_NOTIFICATIONS_ERROR = 'CLEAR_NOTIFICATIONS_ERROR'

export const NOTIFICATION = 'NOTIFICATION'
