// GET ALL
export const GET_ALL_SPACES_REQUEST = 'GET_ALL_SPACES_REQUEST'
export const GET_ALL_SPACES_SUCCESS = 'GET_ALL_SPACES_SUCCESS'
export const GET_ALL_SPACES_ERROR = 'GET_ALL_SPACES_ERROR'

// GET
export const GET_SPACE_REQUEST = 'GET_SPACE_REQUEST'
export const GET_SPACE_SUCCESS = 'GET_SPACE_SUCCESS'
export const GET_SPACE_ERROR = 'GET_SPACE_ERROR'

// POST
export const CREATE_SPACE_REQUEST = 'CREATE_SPACE_REQUEST'
export const CREATE_SPACE_SUCCESS = 'CREATE_SPACE_SUCCESS'
export const CREATE_SPACE_ERROR = 'CREATE_SPACE_ERROR'

// UPDATE
export const UPDATE_SPACE_REQUEST = 'UPDATE_SPACE_REQUEST'
export const UPDATE_SPACE_SUCCESS = 'UPDATE_SPACE_SUCCESS'
export const UPDATE_SPACE_ERROR = 'UPDATE_SPACE_ERROR'

// DELETE
export const DELETE_SPACE_REQUEST = 'DELETE_SPACE_REQUEST'
export const DELETE_SPACE_SUCCESS = 'DELETE_SPACE_SUCCESS'
export const DELETE_SPACE_ERROR = 'DELETE_SPACE_ERROR'
