export const GET_SPACE = 'SPACE:GET_SPACE'
export const SET_SPACE = 'SPACE:SET_SPACE'

export const CREATE_SPACE_REQUEST = 'CREATE_SPACE_REQUEST'
export const CREATE_SPACE_SUCCESS = 'CREATE_SPACE_SUCCESS'
export const CREATE_SPACE_ERROR = 'CREATE_SPACE_ERROR'

export const UPDATE_SPACE_REQUEST = 'UPDATE_SPACE_REQUEST'
export const UPDATE_SPACE_SUCCESS = 'UPDATE_SPACE_SUCCESS'
export const UPDATE_SPACE_ERROR = 'UPDATE_SPACE_ERROR'

export const DELETE_SPACE_REQUEST = 'DELETE_SPACE_REQUEST'
export const DELETE_SPACE_SUCCESS = 'DELETE_SPACE_SUCCESS'
export const DELETE_SPACE_ERROR = 'DELETE_SPACE_ERROR'
