
// GET
export const GET_ALL_PAGES_REQUEST = 'GET_ALL_PAGES_REQUEST'
export const GET_ALL_PAGES_SUCCESS = 'GET_ALL_PAGES_SUCCESS'
export const GET_ALL_PAGES_ERROR = 'GET_ALL_PAGES_ERROR'

// GET ONE
export const GET_PAGE_BY_ID_REQUEST = 'GET_PAGE_BY_ID_REQUEST'
export const GET_PAGE_BY_ID_SUCCESS = 'GET_PAGE_BY_ID_SUCCESS'
export const GET_PAGE_BY_ID_ERROR = 'GET_PAGE_BY_ID_ERROR'

// POST
export const CREATE_PAGE_REQUEST = 'CREATE_PAGE_REQUEST'
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS'
export const CREATE_PAGE_ERROR = 'CREATE_PAGE_ERROR'

export const CREATE_BLOG_PAGE_REQUEST = 'CREATE_BLOG_PAGE_REQUEST'
export const CREATE_BLOG_PAGE_SUCCESS = 'CREATE_BLOG_PAGE_SUCCESS'

// UPDATE
export const UPDATE_PAGE_REQUEST = 'UPDATE_PAGE_REQUEST'
export const UPDATE_PAGE_SUCCESS = 'UPDATE_PAGE_SUCCESS'
export const UPDATE_PAGE_ERROR = 'UPDATE_PAGE_ERROR'

export const UPDATE_BLOG_PAGE_REQUEST = 'UPDATE_BLOG_PAGE_REQUEST'
export const UPDATE_BLOG_PAGE_SUCCESS = 'UPDATE_BLOG_PAGE_SUCCESS'

// DELETE
export const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST'
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS'
export const DELETE_PAGE_ERROR = 'DELETE_PAGE_ERROR'

export const DELETE_BLOG_PAGE_REQUEST = 'DELETE_BLOG_PAGE_REQUEST'
export const DELETE_BLOG_PAGE_SUCCESS = 'DELETE_BLOG_PAGE_SUCCESS'

// CANCEL REQUEST
export const CANCEL_PAGE_BY_ID_REQUEST = 'CANCEL_PAGE_BY_ID_REQUEST(already in store)'

// EXPORT
export const EXPORT_PAGE_TO_PDF = 'EXPORT_PAGE_TO_PDF'
export const EXPORT_PAGE_TO_WORD = 'EXPORT_PAGE_TO_WORD'

// SEND DOC FILE
export const SEND_DOC_FILE_REQUEST = 'SEND_DOC_FILE_REQUEST'
export const SEND_DOC_FILE_SUCCESS = 'SEND_DOC_FILE_SUCCESS'
export const SEND_DOC_ERROR = 'SEND_DOC_ERROR'

// MENTION COMMENT
export const MENTION_COMMENT = 'MENTION_COMMENT'
