
export const GET_SPACE_PERMISSIONS_REQUEST = 'GET_SPACE_PERMISSIONS_REQUEST'
export const GET_SPACE_PERMISSIONS_SUCCESS = 'GET_SPACE_PERMISSIONS_SUCCESS'
export const GET_SPACE_PERMISSIONS_ERROR = 'GET_SPACE_PERMISSIONS_ERROR'

export const UPDATE_SPACE_PERMISSIONS_REQUEST = 'UPDATE_SPACE_PERMISSIONS_REQUEST'
export const UPDATE_SPACE_PERMISSIONS_SUCCESS = 'UPDATE_SPACE_PERMISSIONS_SUCCESS'
export const UPDATE_SPACE_PERMISSIONS_ERROR = 'UPDATE_SPACE_PERMISSIONS_ERROR'

export const ADD_USER_PERMISSIONS_REQUEST = 'ADD_USER_PERMISSIONS_REQUEST'
export const ADD_USER_PERMISSIONS_SUCCESS = 'ADD_USER_PERMISSIONS_SUCCESS'
export const ADD_USER_PERMISSIONS_ERROR = 'ADD_USER_PERMISSIONS_ERROR'

export const ADD_GROUP_PERMISSIONS_REQUEST = 'ADD_GROUP_PERMISSIONS_REQUEST'
export const ADD_GROUP_PERMISSIONS_SUCCESS = 'ADD_GROUP_PERMISSIONS_SUCCESS'
export const ADD_GROUP_PERMISSIONS_ERROR = 'ADD_GROUP_PERMISSIONS_ERROR'

export const REFRESH_AUTH_USER_PERMISSIONS = 'REFRESH_AUTH_USER_PERMISSIONS'
