export const spaceActions = {
  CREATE_SPACE_SUCCESS: 'CREATE_SPACE_SUCCESS',
  UPDATE_SPACE_SUCCESS: 'UPDATE_SPACE_SUCCESS'
}

export const pageActions = {
  CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
  UPDATE_PAGE_SUCCESS: 'UPDATE_PAGE_SUCCESS'
}

export const commentActions = {
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  EDIT_COMMENT_SUCCESS: 'EDIT_COMMENT_SUCCESS'
}
