export const spaceActions = {
  CREATE_SPACE_SUCCESS: 'CREATE_SPACE_SUCCESS',
  UPDATE_SPACE_SUCCESS: 'UPDATE_SPACE_SUCCESS'
}

export const pageActions = {
  CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
  UPDATE_PAGE_SUCCESS: 'UPDATE_PAGE_SUCCESS'
}

export const blogActions = {
  CREATE_BLOG_PAGE_SUCCESS: 'CREATE_BLOG_PAGE_SUCCESS',
  UPDATE_BLOG_PAGE_SUCCESS: 'UPDATE_BLOG_PAGE_SUCCESS'
}
// temporary off
export const commentActions = {
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS_OFF',
  EDIT_COMMENT_SUCCESS: 'EDIT_COMMENT_SUCCESS_OFF'
}
