export const HISTORY_SPACE_SAVE_SUCCESS = 'HISTORY_SPACE_SAVE_SUCCESS'
export const HISTORY_SPACE_SAVE_ERROR = 'HISTORY_SPACE_SAVE_ERROR'

export const HISTORY_PAGE_SAVE_SUCCESS = 'HISTORY_PAGE_SAVE_SUCCESS'
export const HISTORY_PAGE_SAVE_ERROR = 'HISTORY_PAGE_SAVE_ERROR'

export const HISTORY_COMMENT_SAVE_SUCCESS = 'HISTORY_COMMENT_SAVE_SUCCESS'
export const HISTORY_COMMENT_SAVE_ERROR = 'HISTORY_COMMENT_SAVE_ERROR'
