
export const GET_MATCHING_USERS_REQUEST = 'GET_MATCHING_USERS_REQUEST'
export const GET_MATCHING_USERS_SUCCESS = 'GET_MATCHING_USERS_SUCCESS'
export const GET_MATCHING_USERS_ERROR = 'GET_MATCHING_USERS_ERROR'

export const CLEAN_MATCHING_USERS = 'CLEAN_MATCHING_USERS'
