
export const GET_MATCHING_PAGES_REQUEST = 'GET_MATCHING_PAGES_REQUEST'
export const GET_MATCHING_PAGES_SUCCESS = 'GET_MATCHING_PAGES_SUCCESS'
export const GET_MATCHING_PAGES_ERROR = 'GET_MATCHING_PAGES_ERROR'

export const CLEAN_MATCHING_PAGES = 'CLEAN_MATCHING_PAGE'
