export const VERIFICATION = 'VERIFICATION'
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_ERROR = 'VERIFICATION_ERROR'
export const SAVE_USER_IN_SESSION = 'SAVE_USER_IN_SESSION'
